# Generated by Django 5.0.6 on 2025-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('status', models.CharField(choices=[('a_iniciar', 'A Iniciar'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado')], default='a_iniciar', max_length=20)),
            ],
        ),
    ]
