# Generated by Django 5.0.6 on 2025-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_remove_projeto_descricao_projeto_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('a_iniciar', 'A Iniciar'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('revisao', 'Revisão')], default='a_iniciar', max_length=20),
        ),
    ]
