# Generated by Django 5.1.7 on 2025-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_alter_projeto_cliente_alter_projeto_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='status',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
